# -*- coding: utf-8 -*-
"""AIhubhw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OzQgXGqPcVo5kJ9nLwyf0aX102A9GvTE
"""

numb = int(input("Please enter a digit: "))

for x in range(0,numb+1,2):
  print(x)